name: riverpod
description: >
  A simple way to access state from anywhere in your application while robust
  and testable.
version: 0.14.0+3
homepage: https://riverpod.dev
repository: https://github.com/rrousselGit/river_pod

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  collection: ^1.15.0
  freezed_annotation: ^0.14.0
  meta: ^1.3.0
  state_notifier: ^0.7.0

dev_dependencies:
  build_runner: ^1.11.0
  freezed: ^0.14.0
  mockito: ^5.0.0
  test: ^1.16.0
  # test_coverage: ^0.4.3
  trotter: ^2.0.0-dev.1
